name: Python Package using Conda

on: [push]

jobs:
  build:
    name: Build (${{ matrix.os }}, Python ${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Add conda to system path
      run: |
        # Add conda to system path
        echo $CONDA/bin >> $GITHUB_PATH
      shell: bash
    
    - name: Install dependencies (Linux)
      if: runner.os == 'Linux'
      run: |
        conda install pytorch torchvision cpuonly -c pytorch
        python -m pip install --upgrade pip
        pip install pytest pytest-cov flake8
        pip install -e .
      shell: bash

    - name: Install dependencies (Windows)
      if: runner.os == 'Windows'
      run: |
        conda install pytorch torchvision cpuonly -c pytorch
        python -m pip install --upgrade pip
        pip install pytest pytest-cov flake8
        pip install -e .
      shell: cmd
    
    - name: List environment info
      run: |
        conda info
        conda list
        pip list
        python -c "import torch; print(f'PyTorch {torch.__version__}')"
        python -c "import torchvision; print(f'TorchVision {torchvision.__version__}')"
      shell: bash
    
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      shell: bash
    
    - name: Test with pytest
      run: |
        pytest tests/ --cov=convnext_perceptual_loss --cov-report=xml
      shell: bash
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella-${{ matrix.os }}-py${{ matrix.python-version }}
        fail_ci_if_error: false