name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    
    - name: Add conda to system path
      run: |
        echo $CONDA/bin >> $GITHUB_PATH
    
    - name: Install dependencies
      run: |
        conda install pytorch torchvision cpuonly -c pytorch
        python -m pip install --upgrade pip
        pip install pytest pytest-cov flake8
        pip install -e .
    
    - name: List environment info
      run: |
        conda info
        conda list
        pip list
        python -c "import torch; print(f'PyTorch {torch.__version__}')"
        python -c "import torchvision; print(f'TorchVision {torchvision.__version__}')"
    
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Test with pytest
      run: |
        pytest tests/ --cov=convnext_perceptual_loss --cov-report=xml
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
